// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using personapi_dotnet.Models.Entities;

#nullable disable

namespace personapi_dotnet.Migrations
{
    [DbContext(typeof(PersonaDbContext))]
    partial class PersonaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Estudio", b =>
                {
                    b.Property<int>("IdProf")
                        .HasColumnType("int")
                        .HasColumnName("id_prof");

                    b.Property<int>("CcPer")
                        .HasColumnType("int")
                        .HasColumnName("cc_per");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Univer")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("univer");

                    b.HasKey("IdProf", "CcPer")
                        .HasName("PK__estudios__FB3F71A6223C4A76");

                    b.HasIndex("CcPer");

                    b.ToTable("estudios", (string)null);
                });

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Persona", b =>
                {
                    b.Property<int>("Cc")
                        .HasColumnType("int")
                        .HasColumnName("cc");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("apellido");

                    b.Property<byte?>("Edad")
                        .HasColumnType("tinyint")
                        .HasColumnName("edad");

                    b.Property<string>("Genero")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("genero")
                        .IsFixedLength();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombre");

                    b.HasKey("Cc")
                        .HasName("PK__persona__3213E83FC333E091");

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Profesion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Des")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("des");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(90)
                        .IsUnicode(false)
                        .HasColumnType("varchar(90)")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("PK__profesio__3213E83F50854D8C");

                    b.ToTable("profesion", (string)null);
                });

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Telefono", b =>
                {
                    b.Property<string>("Num")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("num");

                    b.Property<int>("Duenio")
                        .HasColumnType("int")
                        .HasColumnName("duenio");

                    b.Property<string>("Oper")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("oper");

                    b.HasKey("Num")
                        .HasName("PK__telefono__DF908D65F944ADC4");

                    b.HasIndex("Duenio");

                    b.ToTable("telefono", (string)null);
                });

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Estudio", b =>
                {
                    b.HasOne("personapi_dotnet.Models.Entities.Persona", "CcPerNavigation")
                        .WithMany("Estudios")
                        .HasForeignKey("CcPer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__estudios__cc_per__3F466844");

                    b.HasOne("personapi_dotnet.Models.Entities.Profesion", "IdProfNavigation")
                        .WithMany("Estudios")
                        .HasForeignKey("IdProf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__estudios__id_pro__3E52440B");

                    b.Navigation("CcPerNavigation");

                    b.Navigation("IdProfNavigation");
                });

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Telefono", b =>
                {
                    b.HasOne("personapi_dotnet.Models.Entities.Persona", "DuenioNavigation")
                        .WithMany("Telefonos")
                        .HasForeignKey("Duenio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__telefono__duenio__3B75D760");

                    b.Navigation("DuenioNavigation");
                });

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Persona", b =>
                {
                    b.Navigation("Estudios");

                    b.Navigation("Telefonos");
                });

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Profesion", b =>
                {
                    b.Navigation("Estudios");
                });
#pragma warning restore 612, 618
        }
    }
}
