version: "3.8"

services:
  personapi-app:
    container_name: personapi-app
    build: .
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    environment:
      # Use the service name 'db' as the server name
      - ConnectionStrings__DefaultConnection=Server=db;Database=persona_db;User ID=sa;Password=Password123;TrustServerCertificate=True;MultipleActiveResultSets=true
    depends_on:
      - db
    # Add entrypoint to wait for DB
    entrypoint: ["sh", "-c", "sleep 10 && dotnet personapi-dotnet.dll"]

  db:
    container_name: sqlserver-db
    image: mcr.microsoft.com/mssql/server:2022-latest # SQL Server 2022 Linux image
    ports:
      - "1433:1433" # Map host port 1433 to container port 1433 if direct DB access from host is needed
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    volumes:
      - sqlserver_data:/var/opt/mssql # Persist database data

volumes:
  sqlserver_data:
